[package]
name = "eclair-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eclair = { path = "../openzl/eclair" }
openzl-plugin-arkworks = { path = "../openzl/plugins/arkworks" }
